POST http://localhost:5050/reviews HTTP/1.1
content-type: application/json

# {
#     "question": "What is the capital of Virginia?",
#     "answerChoises": "'Boston', 'Austin', 'Annapolis', 'Chicago', 'none",
#     "answer": "none",
#      "Author" : "Holi "
# }

    {
       "userId":3,
       "title": "quasi id et eos tenetur aut quo autem",
       "text":  "odit magnam ut saepe sed non qui\ntempora atque nihil\naccusamus illum doloribus",
       "review_id": 4
    }
